- name: Copy rabbit mq sevice file
  ansible.builtin.template:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: Install RabbitMQ
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: present

- name: start RabbitMQ service
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: started

- name: add application user
  ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123 ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"