- name: install python packages
  ansible.builtin.dnf:
    name: 
      - python3
      - gcc
      - python3-devel
    state: present

- name: include artifact download
  ansible.buitlin.include_tasks: 